apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app.kubernetes.io/name: echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: echo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo
    spec:
      # 「app.kubernetes.io/name=echo」のラベルがついているpodがデプロイされているnodeにはデプロイしない
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: # ルールを満たさない限りnodeにpodを配置しない
            - labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/name" # app.kubernetes.io/name=echoのpod
                    operator: In
                    values:
                    - echo
              topologyKey: "kubernetes.io/hostname" # nodeに必ずつけられるラベル。条件を適用する対象を指定
      containers:
      - name: nginx
        image: ghcr.io/gihyodocker/simple-nginx-proxy:v0.1.0
        env:
        - name: NGINX_PORT
          value: "80"
        - name: SERVER_NAME
          value: "localhost"
        - name: BACKEND_HOST
          value: "localhost:8080"
        - name: BACKEND_MAX_FAILS
          value: "3"
        - name: BACKEND_FAIL_TIMEOUT
          value: "10s"
        ports:
          - containerPort: 80
      - name: echo
        image:  ghcr.io/gihyodocker/echo:v0.1.0
        ports:
        - containerPort: 8080